[package]
name = "csgrs"
version = "0.6.0"
edition = "2021"
description = "Constructive solid geometry on meshes using BSP trees in Rust"
authors = ["Timothy Schmidt <timschmidt@gmail.com>",]
license = "MIT"
repository = "https://github.com/timschmidt/csgrs"
readme = "readme.md"

[dependencies]
cavalier_contours = "0.4.0"
chull = "0.2.4"
earclip = "1.1.0"
meshtext = { version = "0.3.1", features = ["owned"] }
nalgebra = "0.33"
parry3d-f64 = "0.18.0"
rapier3d-f64 = "0.23.0"
rayon = { version = "1.7", optional = true }
stl_io = "0.8.3"

[features]
default = []
parallel = ["rayon"]
