[package]
name = "csgrs"
version = "0.2.0"
edition = "2021"
authors = ["Timothy Schmidt <timschmidt@gmail.com>",]

[dependencies]
chull = "0.2.4"
nalgebra = "0.33"
parry3d-f64 = "0.18.0"
rapier3d-f64 = "0.23.0"
rayon = { version = "1.7", optional = true }

[features]
default = []
parallel = ["rayon"]
