[package]
name = "csg-rs"
version = "0.1.0"
edition = "2021"
authors = ["Timothy Schmidt <timschmidt@gmail.com>",]

[dependencies]
chull = "0.2.4"
nalgebra = "0.33"
rayon = { version = "1.7", optional = true }

[features]
default = []
parallel = ["rayon"]
