name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

  # ---------- crate-specific switches ----------
  # Exactly ONE of {f32, f64}:
  FLOAT_FEATURE: f32
  # Exactly ONE of {earcut, delaunay}:
  TESSELLATION_FEATURE: earcut

  # Extra features you want in every build:
  EXTRA_FEATURES: |
    parallel
    stl-io
    svg-io
    dxf-io
    truetype-text
    hershey-text
    image-io

  # Convenience: the complete list we’ll pass to Cargo
  FEATURES: "${{ env.FLOAT_FEATURE }} ${{ env.TESSELLATION_FEATURE }} ${{ env.EXTRA_FEATURES }}"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Check
        run: cargo check --no-default-features --features "${FEATURES}"

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --lib --no-default-features --features "${FEATURES}"

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Run Fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --lib --no-default-features --features "${FEATURES}" -- -D warnings

  style:
    name: Check spelling and semver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove untracked files
        run: git clean -df

      - name: Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: csgrs
          no-default-features: true
          features: ${{ env.FLOAT_FEATURE }},${{ env.TESSELLATION_FEATURE }},${{ env.EXTRA_FEATURES }}

      - name: Check spelling
        run: |
          if ! command -v typos >/dev/null; then
            cargo install typos-cli
          fi
          typos
